### PR TITLE
[Issue #3] Expand string package

### PR DESCRIPTION
**Pull request by sadliak**
Hey, I implemented a bunch of methods from string package, as discussed in #3  .
To be precise, I implemeted those methods:
+ strings.Count
+ strings.Contains
+ strings.ContainsAny
+ strings.LastIndex
+ strings.LastIndexAny
+ strings.Trim
+ strings.TrimSuffix
+ strings.TrimPrefix
+ strings.TrimLeft
+ strings.TrimRight 
+ strings.SplitAfter
+ strings.SplitN
+ strings.SplitAfterN

I have read the project's contributing guidelines and inherited the right commit messages style for the project. Also, I have run different checks using [goreportcard](https://goreportcard.com/report/github.com/alexsadliak/ligo), my changes have not introduced any result degradations.

Hope, I will be of any help for you :smile:

### CODE REVIEW

**Review by aki237 — COMMENTED** [review]
Everything seems perfect. But in ligo I have added support only for int64, so for the functions that returns int convert them to int64 and return them. Like in `vmStringCount`, `vmStringContainsAny` etc.,

like

```go
return ligo.Variable{Type: ligo.TypeInt, Value: int64(strings.LastIndex(str, substr))}
```

**Comment by sadliak** [comment]
Okay, I will fix that in a moment.

**Review by aki237 — APPROVED** [review]
perfect. Let me check it and merge it.

**Comment by sadliak** [comment]
I plan to add other string methods also, may I do it in a separate PR?

**Comment by aki237** [comment]
Sure.

**Comment by sadliak** [comment]
I thought about it and decided to add other string related functions in this PR.
I will help you with url package in another one.

**Comment by aki237** [comment]
Another I have made a blunder.
You have to `return vm.Throw(...)`
That construct was a new addition, so didn't see that.
I'll take care of that in the current PR. But in the future ones return `vm.Throw`.

**Comment by aki237** [comment]
Hey and another thing, make a new branch for every PR. You have pushed a new commit I cannot merge it right now. try to revert to the commits and work it in a current branch

**Comment by sadliak** [comment]
Okay, sorry if it caused you any trouble. I can change `vm.Throw(...)` myself if it needed.

**Comment by aki237** [comment]
No no I'll change it in my master. Try contacting me on gitter.

**Pull request merged**
