### PR TITLE
[Issue #3] Add support for string join method

### PR DESCRIPTION
**Pull request by sadliak**
Hey, I have left one method from string package not implemented in previous [PR](#12 ).
Here is an implementation of `strings.Join` method from the issue #3

### CODE REVIEW

**Review by aki237 — COMMENTED** [review]
Good PR. But we don't need to have a []ligo.Variable.
The call will be like
```lisp
(string-join "Hello" " " "World" "!!") 
```
So `a[0]` is `"Hello"`,
`a[1]` is `" "`
`a[2]` is `"World"`
`a[3]` is `"!!"`

So this function doesn't need to have a argument number check. Just loop through a and throw if one of it is not a string...

**Comment by sadliak** [comment]
Strings.Join(...) from Go standard library does not work in this way. However, I can implement needed behavior.

**Comment by aki237** [comment]
Actually can you implement it...

**Comment by sadliak** [comment]
Probably, you are misunderstood. You could check out the [docs](https://golang.org/pkg/strings/#Join).

**Pull request merged**
